apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cert-manager-cronjob
  namespace: cert-manager
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-cert-manager-cronjob
          restartPolicy: Never
          containers:
            - name: hyperkube
              image: bitnami/kubectl:latest
              command: [ "/bin/bash","-c" ]
              args:
                - for i in $(kubectl get ns -o jsonpath='{.items[*].metadata.name}'); do kubectl get secret -o json --namespace cert-manager wildcard.cmtbj9qp.visol.dev --export | jq 'del(.metadata.namespace)' | kubectl apply -n ${i} -f -;  done